### ISSUE TITLE
Chapter 2: Arrow functions

### ISSUE THREAD

**Issue by chris-tse** [AlbertoMontalesi/The-complete-guide-to-modern-JavaScript#12]
Hey, great work on the book!

I wanted to mention that in this chapter, you introduce one way of creating functions at the top but not the other. Since there is no section introducing what functions are, it may be worthwhile to introduce it here.

```js
function greeting(name) {
  return "hello " + name;
}
```
I see it's used in an example further down, but having it at the top could be beneficial for beginners.

**Comment by AlbertoMontalesi** [comment]
Hi, sorry for the late reply. This book is available in two version: free and paid. The free version includes the core of the book which covers ES6 to ES2109. The Paid version includes an introduction to JavaScript and TypeScript. Declaring functions is found in that 'introduction to javascript' part of the book. This free version implies some prior JavaScript knowledge. 

Thank you for reading !
