### ISSUE TITLE
Spellchecks and Tweaks

### ISSUE THREAD

**Issue by AlbertoMontalesi** [AlbertoMontalesi/The-complete-guide-to-modern-JavaScript#21]
As a non native speaker there may still be spelling errors or others mistake in the book. If anybody wants to help that would be great.

**Comment by guntbert** [comment]
Hi, where do you want to get reports about typos in chapters that are not here on github (like chapter 1 in the released version of your book)?

**Comment by AlbertoMontalesi** [comment]
I guess you can just open a single issue and paste them as you find them. Thanks a lot for the help!
