### ISSUE TITLE
Formatting suggestions

### ISSUE THREAD

**Issue by guntbert** [AlbertoMontalesi/The-complete-guide-to-modern-JavaScript#23]
Hi @AlbertoMontalesi , big thanks for this book - it meets my needs exactly :bowing_man: 
I have three suggestions to make it easier to read (I am reading the pdf for now)

1. Apply page headers/footers to show the current chapter
2. Prevent code blocks from overflowing to the next page
3. Tweak the property *Title* of the pdf downloaded from leanpub - currently it is `Final book`

best regards
Guntbert

**Comment by AlbertoMontalesi** [comment]
Thanks a lot for the positive feedback and help!.

Regarding your points:
1. This is definitely something I'm going to address while I get some time to work on the book
2. Same as above
3. I believe this is already not an issue, I've updated the pdf on Leanpub on the 9th of October, did you purchase it before that date?

**Comment by guntbert** [comment]
I bought it three days ago and tested the download immediately before opening this issue. The *epub* is fine but the *pdf* has that weird Title.

**Comment by AlbertoMontalesi** [comment]
Oh, that's weird because I just downloaded the file i uploaded on leanpub and the title was correct. I'll check with them, they already had some issues last time where the sample was not updating properly so maybe it's another bug in the system

**Comment by AlbertoMontalesi** [comment]
@guntbert  I've had a talk with Leanpub and it seems to be a potential bug as the title of the files should always reflect the slug of the book page, in this case it should have been 'thecompleteguidetomodernjavascript2019.pdf'

**Comment by guntbert** [comment]
Indeed, the currently available version from Oct 30th has the correct title :clap:
