### ISSUE TITLE
translation publication inquiry

### ISSUE THREAD

**Issue by anemochore** [AlbertoMontalesi/The-complete-guide-to-modern-JavaScript#26]
Hi, I work for Hanbit Media, Inc., the largest IT publisher in Korea.
We have translated and published many English programming books here.
I think your book is also very helpful to Korean programmer readers.
Do you have any plan for publication in foreign countries?
If you are willing, I'll let our copyrights manager contact you to discuss the details.
I appreciate your quick response.

**Comment by AlbertoMontalesi** [comment]
@anemochore hi, sorry for the very late reply, i don't often check issues and the notification got lost. Please send an email to alberto.montalesi@outlook.it to discuss more. Thank you!

**Comment by anemochore** [comment]
@AlbertoMontalesi Oops I was late too. I'll send an email to you. Thanks!
